### ISSUE TITLE
rake china_regions:import导入数据问题

### ISSUE THREAD

**Issue by yangjindong** [encoreshao/china_regions#8]
当运行rake china_regions:import时，import task莫名其妙的会被执行2次。

当把这个import 重名后，用新的名称执行时，则可以正确执行1次。

不知什么地方出了问题？

**Comment by encoreshao** [comment]
@yangjindong - 已修复!  

> 错误原因:  rails5默认可以加载到gem中的tasks, 我们可以不用把自定义task复制到我们项目中。

所以我修改gem中(tasks)目录的名字, 请更新到最新版本 - `0.4.4`.

Thank you!
